/**
 * Media persistence helpers: saving generated bytes into the session workspace.
 *
 * The plugin writes with Node's own filesystem primitives under the calling
 * session's workspace cwd (`exec.agent.session.header.cwd`) plus a configured
 * relative `saveDir`. The save dir is validated at plugin load: it must stay
 * relative and contain no `..` segments, so a configured value can never
 * escape the workspace root.
 */

import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { extname, isAbsolute, join } from 'node:path'

/** Extension map for the content types grok2api realistically returns. */
const CONTENT_TYPE_EXT = {
  'image/png': '.png',
  'image/jpeg': '.jpg',
  'image/webp': '.webp',
  'image/gif': '.gif',
  'video/mp4': '.mp4',
  'video/webm': '.webm',
  'video/quicktime': '.mov',
}

/**
 * Validate a configured save dir: relative, non-empty, no parent segments.
 * @param {string} saveDir - the configured value.
 * @throws {Error} when the value could escape the workspace root.
 */
export function assertSafeSaveDir(saveDir) {
  if (typeof saveDir !== 'string' || saveDir.trim().length === 0) {
    throw new Error('grok2api-media-tool: config saveDir must be a non-empty string')
  }
  if (isAbsolute(saveDir) || /^[a-zA-Z]:[\\/]/.test(saveDir)) {
    throw new Error('grok2api-media-tool: config saveDir must be a relative path')
  }
  if (saveDir.split(/[\\/]/).includes('..')) {
    throw new Error('grok2api-media-tool: config saveDir must not contain ".."')
  }
  return saveDir.trim()
}

/** Pick a file extension from the response content type, else the URL, else a kind default. */
export function extFor(kind, contentType, url) {
  if (contentType) {
    const mediaType = contentType.split(';')[0].trim().toLowerCase()
    if (CONTENT_TYPE_EXT[mediaType]) return CONTENT_TYPE_EXT[mediaType]
  }
  if (url) {
    const match = /\.([a-zA-Z0-9]{1,5})(?:[?#]|$)/.exec(url)
    if (match) return `.${match[1].toLowerCase()}`
  }
  return kind === 'video' ? '.mp4' : '.png'
}

/** The calling session's workspace root, or undefined for a caller without one. */
export function workspaceRootFor(exec) {
  const cwd = exec?.agent?.session?.header?.cwd
  return typeof cwd === 'string' && cwd.length > 0 ? cwd : undefined
}

/** Hosts that can only be the dsh host itself (loopback media route). */
const LOCAL_MEDIA_HOSTS = new Set(['127.0.0.1', 'localhost', '::1', '[::1]', '0.0.0.0'])

/** The root-relative media route this plugin serves (kept in sync with media-proxy.js). */
const MEDIA_ROUTE_PREFIX = '/grok2api-media/'

/**
 * Turn a media-route URL (root-relative or loopback absolute) back into the
 * absolute file path it signs. Non-media URLs return undefined.
 * @param {string} value - URL or path to inspect.
 * @returns {string | undefined} the local file path, or undefined.
 */
export function localMediaPathFromUrl(value) {
  if (typeof value !== 'string' || value.length === 0) return undefined
  let url
  try {
    url = new URL(value, 'http://local.invalid')
  } catch {
    return undefined
  }
  if (!url.pathname.startsWith(MEDIA_ROUTE_PREFIX)) return undefined
  const host = url.hostname.toLowerCase()
  const isRootRelative = value.startsWith('/')
  if (!isRootRelative && !LOCAL_MEDIA_HOSTS.has(host)) return undefined
  try {
    return decodeURIComponent(url.pathname.slice(MEDIA_ROUTE_PREFIX.length))
  } catch {
    return undefined
  }
}

/**
 * Resolve a recognize_image input into a value grok2api's chat endpoint can
 * consume: a data URL for local files and media-route URLs, or the original
 * http(s)/data URL untouched.
 *
 * @param {string} image - http(s) URL, data URL, or local file path (absolute or relative to the session workspace).
 * @param {object} [exec] - tool execution context, used to resolve relative paths.
 * @returns {Promise<string>} an image data URL or an http(s)/data URL.
 * @throws {Error} when a local file cannot be read.
 */
export async function imageDataUrlForInput(image, exec) {
  const value = typeof image === 'string' ? image.trim() : ''
  if (value.length === 0) throw new Error('image must be a non-empty URL, data URL, or local path')
  const mediaPath = localMediaPathFromUrl(value)
  if (mediaPath !== undefined) {
    try {
      const bytes = await readFile(mediaPath)
      const mime = CONTENT_TYPE_EXT[extname(mediaPath).toLowerCase()] ?? 'image/png'
      return `data:${mime};base64,${bytes.toString('base64')}`
    } catch (error) {
      throw new Error(`cannot read media-route image ${JSON.stringify(value)}: ${String(error?.message ?? error)}`)
    }
  }
  if (/^data:image\//i.test(value) || /^https?:\/\//i.test(value)) return value
  const root = workspaceRootFor(exec)
  const path = isAbsolute(value) ? value : (root ? join(root, value) : value)
  try {
    const bytes = await readFile(path)
    const mime = CONTENT_TYPE_EXT[extname(path).toLowerCase()] ?? 'image/png'
    return `data:${mime};base64,${bytes.toString('base64')}`
  } catch (error) {
    throw new Error(`cannot read image file ${JSON.stringify(value)}: ${String(error?.message ?? error)}`)
  }
}


/**
 * Write generated bytes under `<workspace>/<saveDir>/grok2api-<kind>-<timestamp>-<index><ext>`.
 * @returns {Promise<string>} the absolute saved path.
 * @throws {Error} when the workspace root is unavailable or the write fails.
 */
export async function saveMedia(exec, saveDir, kind, bytes, index, contentType, sourceUrl) {
  const root = workspaceRootFor(exec)
  if (root === undefined) {
    throw new Error('session workspace cwd is unavailable; cannot save media locally')
  }
  const dir = join(root, saveDir)
  await mkdir(dir, { recursive: true })
  const stamp = new Date().toISOString().replace(/[-:T]/g, '').slice(0, 15)
  const file = join(dir, `grok2api-${kind}-${stamp}-${index}${extFor(kind, contentType, sourceUrl)}`)
  await writeFile(file, bytes)
  return file
}

/**
 * Download a media URL into memory, abortable and bounded by the request timeout.
 * @returns {Promise<{ bytes: Buffer, contentType?: string }>}
 */
export async function downloadBytes(url, cfg, signal) {
  const headers = {}
  const apiKey = typeof cfg.resolveApiKey === 'function'
    ? await cfg.resolveApiKey()
    : cfg.apiKey
  if (apiKey) headers.authorization = `Bearer ${apiKey}`
  // Media files (videos especially) are large: give the download its own
  // budget, at least the per-request timeout and at most the download window
  // the video poll loop reserved.
  const mediaTimeoutMs = Math.max(cfg.requestTimeoutMs, cfg.mediaDownloadTimeoutMs ?? 300000)
  const response = await fetch(url, {
    headers,
    signal: AbortSignal.any([signal, AbortSignal.timeout(mediaTimeoutMs)]),
  })
  if (!response.ok) throw new Error(`downloading media failed: HTTP ${response.status} ${response.statusText}`)
  const buffer = Buffer.from(await response.arrayBuffer())
  return { bytes: buffer, contentType: response.headers.get('content-type') ?? undefined }
}

/** Decode a base64 image body, tolerating an optional `data:<mime>;base64,` prefix. */
export function decodeB64(value) {
  const cleaned = String(value).replace(/^data:[^;,]*;base64,/, '')
  return Buffer.from(cleaned, 'base64')
}
